# Generated by Django 3.0.6 on 2020-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_remove_user_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderN', models.CharField(max_length=50)),
                ('receiverN', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
